CREATE TABLE IF NOT EXISTS `characters`
(
    `id`                   int(11)             NOT NULL AUTO_INCREMENT,
    `accountid`            int(11)             NOT NULL DEFAULT '0',
    `world`                int(11)             NOT NULL DEFAULT '0',
    `name`                 varchar(13)         NOT NULL DEFAULT '',
    `level`                int(11)             NOT NULL DEFAULT '1',
    `exp`                  int(11)             NOT NULL DEFAULT '0',
    `gachaexp`             int(11)             NOT NULL DEFAULT '0',
    `str`                  int(11)             NOT NULL DEFAULT '12',
    `dex`                  int(11)             NOT NULL DEFAULT '5',
    `luk`                  int(11)             NOT NULL DEFAULT '4',
    `int`                  int(11)             NOT NULL DEFAULT '4',
    `hp`                   int(11)             NOT NULL DEFAULT '50',
    `mp`                   int(11)             NOT NULL DEFAULT '5',
    `maxhp`                int(11)             NOT NULL DEFAULT '50',
    `maxmp`                int(11)             NOT NULL DEFAULT '5',
    `meso`                 int(11)             NOT NULL DEFAULT '0',
    `hpMpUsed`             int(11) unsigned    NOT NULL DEFAULT '0',
    `job`                  int(11)             NOT NULL DEFAULT '0',
    `skincolor`            int(11)             NOT NULL DEFAULT '0',
    `gender`               int(11)             NOT NULL DEFAULT '0',
    `fame`                 int(11)             NOT NULL DEFAULT '0',
    `fquest`               int(11)             NOT NULL DEFAULT '0',
    `hair`                 int(11)             NOT NULL DEFAULT '0',
    `face`                 int(11)             NOT NULL DEFAULT '0',
    `ap`                   int(11)             NOT NULL DEFAULT '0',
    `sp`                   varchar(128)        NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0',
    `map`                  int(11)             NOT NULL DEFAULT '0',
    `spawnpoint`           int(11)             NOT NULL DEFAULT '0',
    `gm`                   tinyint(1)          NOT NULL DEFAULT '0',
    `party`                int(11)             NOT NULL DEFAULT '0',
    `buddyCapacity`        int(11)             NOT NULL DEFAULT '25',
    `createdate`           timestamp           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `rank`                 int(10) unsigned    NOT NULL DEFAULT '1',
    `rankMove`             int(11)             NOT NULL DEFAULT '0',
    `jobRank`              int(10) unsigned    NOT NULL DEFAULT '1',
    `jobRankMove`          int(11)             NOT NULL DEFAULT '0',
    `guildid`              int(10) unsigned    NOT NULL DEFAULT '0',
    `guildrank`            int(10) unsigned    NOT NULL DEFAULT '5',
    `messengerid`          int(10) unsigned    NOT NULL DEFAULT '0',
    `messengerposition`    int(10) unsigned    NOT NULL DEFAULT '4',
    `mountlevel`           int(9)              NOT NULL DEFAULT '1',
    `mountexp`             int(9)              NOT NULL DEFAULT '0',
    `mounttiredness`       int(9)              NOT NULL DEFAULT '0',
    `omokwins`             int(11)             NOT NULL DEFAULT '0',
    `omoklosses`           int(11)             NOT NULL DEFAULT '0',
    `omokties`             int(11)             NOT NULL DEFAULT '0',
    `matchcardwins`        int(11)             NOT NULL DEFAULT '0',
    `matchcardlosses`      int(11)             NOT NULL DEFAULT '0',
    `matchcardties`        int(11)             NOT NULL DEFAULT '0',
    `MerchantMesos`        int(11)                      DEFAULT '0',
    `HasMerchant`          tinyint(1)                   DEFAULT '0',
    `equipslots`           int(11)             NOT NULL DEFAULT '24',
    `useslots`             int(11)             NOT NULL DEFAULT '24',
    `setupslots`           int(11)             NOT NULL DEFAULT '24',
    `etcslots`             int(11)             NOT NULL DEFAULT '24',
    `familyId`             int(11)             NOT NULL DEFAULT '-1',
    `monsterbookcover`     int(11)             NOT NULL DEFAULT '0',
    `allianceRank`         int(10)             NOT NULL DEFAULT '5',
    `vanquisherStage`      int(11) unsigned    NOT NULL DEFAULT '0',
    `ariantPoints`         int(11) unsigned    NOT NULL DEFAULT '0',
    `dojoPoints`           int(11) unsigned    NOT NULL DEFAULT '0',
    `lastDojoStage`        int(10) unsigned    NOT NULL DEFAULT '0',
    `finishedDojoTutorial` tinyint(1) unsigned NOT NULL DEFAULT '0',
    `vanquisherKills`      int(11) unsigned    NOT NULL DEFAULT '0',
    `summonValue`          int(11) unsigned    NOT NULL DEFAULT '0',
    `partnerId`            int(11)             NOT NULL DEFAULT '0',
    `marriageItemId`       int(11)             NOT NULL DEFAULT '0',
    `reborns`              int(5)              NOT NULL DEFAULT '0',
    `PQPoints`             int(11)             NOT NULL DEFAULT '0',
    `dataString`           varchar(64)         NOT NULL DEFAULT '',
    `lastLogoutTime`       timestamp           NOT NULL DEFAULT '2015-01-01 05:00:00',
    `lastExpGainTime`      timestamp           NOT NULL DEFAULT '2015-01-01 05:00:00',
    `partySearch`          tinyint(1)          NOT NULL DEFAULT '0',
    `jailexpire`           bigint(20)          NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    KEY `accountid` (`accountid`),
    KEY `party` (`party`),
    KEY `ranking1` (`level`, `exp`),
    KEY `ranking2` (`gm`, `job`),
    INDEX (id, accountid, world),
    INDEX (id, accountid, name)
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1
  PACK_KEYS = 0
  AUTO_INCREMENT = 1
