CREATE TABLE IF NOT EXISTS `mts_items`
(
    `id`           int(10) unsigned NOT NULL AUTO_INCREMENT,
    `tab`          int(11)          NOT NULL DEFAULT '0',
    `type`         int(11)          NOT NULL DEFAULT '0',
    `itemid`       int(10) unsigned NOT NULL DEFAULT '0',
    `quantity`     int(11)          NOT NULL DEFAULT '1',
    `seller`       int(11)          NOT NULL DEFAULT '0',
    `price`        int(11)          NOT NULL DEFAULT '0',
    `bid_incre`    int(11)                   DEFAULT '0',
    `buy_now`      int(11)                   DEFAULT '0',
    `position`     int(11)                   DEFAULT '0',
    `upgradeslots` int(11)                   DEFAULT '0',
    `level`        int(11)                   DEFAULT '0',
    `itemlevel`    int(11)          NOT NULL DEFAULT '1',
    `itemexp`      int(11) unsigned NOT NULL DEFAULT '0',
    `ringid`       int(11)          NOT NULL DEFAULT '-1',
    `str`          int(11)                   DEFAULT '0',
    `dex`          int(11)                   DEFAULT '0',
    `int`          int(11)                   DEFAULT '0',
    `luk`          int(11)                   DEFAULT '0',
    `hp`           int(11)                   DEFAULT '0',
    `mp`           int(11)                   DEFAULT '0',
    `watk`         int(11)                   DEFAULT '0',
    `matk`         int(11)                   DEFAULT '0',
    `wdef`         int(11)                   DEFAULT '0',
    `mdef`         int(11)                   DEFAULT '0',
    `acc`          int(11)                   DEFAULT '0',
    `avoid`        int(11)                   DEFAULT '0',
    `hands`        int(11)                   DEFAULT '0',
    `speed`        int(11)                   DEFAULT '0',
    `jump`         int(11)                   DEFAULT '0',
    `locked`       int(11)                   DEFAULT '0',
    `isequip`      int(1)                    DEFAULT '0',
    `owner`        varchar(16)               DEFAULT '',
    `sellername`   varchar(16)      NOT NULL,
    `sell_ends`    varchar(16)      NOT NULL,
    `transfer`     int(2)                    DEFAULT '0',
    `vicious`      int(2) unsigned  NOT NULL DEFAULT '0',
    `flag`         int(2) unsigned  NOT NULL DEFAULT '0',
    `expiration`   bigint(20)       NOT NULL DEFAULT '-1',
    `giftFrom`     varchar(26)      NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = latin1
  AUTO_INCREMENT = 1
